name: Feature Request
description: File a bug report.
title: "[Feature Request]: "
labels: ["feature"]
assignees:
  - Stackclash
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and consise description of the feature you would like to see and how it work.
      placeholder: Describe the feature you would like to see.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Why would this feature be useful?
    validations:
      required: false
