site_name: TTRPG Audio Manager
site_url: https://stackclash.github.io/obsidian-ttrpg-audio-manager
repo_url: https://github.com/Stackclash/obsidian-ttrpg-audio-manager
edit_uri: blob/main/docs/
remote_branch: gh-pages
docs_dir: ./pages
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Settings: settings.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  features:
    - toc.integrate
plugins:
  - include-markdown
markdown_extensions:
  - github-callouts